import type { Metadata } from 'next';
import './globals.css';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import { ThemeProvider } from '@mui/material/styles';
import theme from '@/src/shared/config/mui/theme';
import 'modern-normalize';
import { PropsWithChildren } from 'react';
import MasterContextProvider from '@/src/app/MasterContextProvider/ui/MasterContextProvider';

export const metadata: Metadata = {
	title: 'YouReader - твоя любимая PDF-читалка',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }: PropsWithChildren) {
	return (
		<html lang="ru">
			<body>
				<AppRouterCacheProvider>
					<ThemeProvider theme={theme}>
						<MasterContextProvider>{children}</MasterContextProvider>
					</ThemeProvider>
				</AppRouterCacheProvider>
			</body>
		</html>
	);
}
