import type { Metadata } from 'next';
import './globals.css';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import { ThemeProvider } from '@mui/material/styles';
import theme from '@/src/shared/config/mui/theme';
import 'modern-normalize';
import { PropsWithChildren } from 'react';
import { ProfileProvider } from '@/src/shared/lib/hooks/useStoreProfile';
import { MobileMenuProvider } from '@/src/shared/lib/hooks/useMobileMenu';
import { AlertProvider } from '@/src/shared/lib/hooks/useAlert';

export const metadata: Metadata = {
	title: 'YouReader - твоя любимая PDF-читалка',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }: PropsWithChildren) {
	return (
		<html lang="ru">
			<body>
				<AppRouterCacheProvider>
					<ThemeProvider theme={theme}>
						<MobileMenuProvider>
							<AlertProvider>
								<ProfileProvider>{children}</ProfileProvider>
							</AlertProvider>
						</MobileMenuProvider>
					</ThemeProvider>
				</AppRouterCacheProvider>
			</body>
		</html>
	);
}
