import type { Metadata } from 'next';
import './globals.css';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import { ThemeProvider } from '@mui/material/styles';
import Header from '@/src/widgets/Header';
import theme from '@/theme';
import 'modern-normalize';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="ru">
			<body>
				<AppRouterCacheProvider>
					<ThemeProvider theme={theme}>
						<div id="app">
							<Header />
							{children}
						</div>
					</ThemeProvider>
				</AppRouterCacheProvider>
			</body>
		</html>
	);
}
