import type { Metadata } from 'next';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import { ThemeProvider } from '@mui/material/styles';
import theme from '@/theme';
import 'modern-normalize';

export const metadata: Metadata = {
	title: 'YouReader - твоя любимая PDF-читалка',
	description: 'Generated by create next app',
};

export default function ReaderLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="ru">
			<body>
				<AppRouterCacheProvider>
					<ThemeProvider theme={theme}>
						<div id="app">{children}</div>
					</ThemeProvider>
				</AppRouterCacheProvider>
			</body>
		</html>
	);
}
