import type { Metadata } from 'next';
import 'modern-normalize';

export const metadata: Metadata = {
	title: 'YouReader - твоя любимая PDF-читалка',
	description: 'Generated by create next app',
};

export default function ReaderLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return <div>{children}</div>;
}
